Improved contribute section
AlmaLinux/wiki pull request #33
Opened 2021-06-28 16:00 UTC by iseletsk

Added links to chat
Added section to links help wanted to Contribute

2021-06-28 16:43 UTC, andrewlukoshko requested changes

2021-06-28 16:43 UTC, andrewlukoshko commented on docs/sigs/Cloud.md
> +If you can help, please join us at [Core SIG on Mattermost](https://chat.almalinux.org/almalinux/channels/sigcore)
I believe here should be https://chat.almalinux.org/almalinux/channels/sigcloud

2021-06-30 07:12 UTC, srbala reviewed
minor text change ...

2021-06-30 07:12 UTC, srbala commented on docs/Contribute.md
> +- Help with our [cloud infrastructure maintenance](/sigs/Cloud.html#help-wanted)
Help with our [Cloud Infrastructure Group]

just to follow the same as Core

2021-07-04 16:04 UTC, merged