Adding Help and Support page
AlmaLinux/wiki pull request #361
Opened 2024-02-28 19:40 UTC by sboldyreva

2024-03-01 18:34 UTC, codyro requested changes
Made some suggestions. I'm open to feedback :).

2024-03-01 18:34 UTC, codyro commented on docs/Help-and-Support.md
> +### Chats
> Chats

to

> Community Chat

2024-03-01 18:34 UTC, codyro commented on docs/Help-and-Support.md
> +AlmaLinux Chats allows users to communicate on various channels, each with its specific topics like Packaging, Cloud, and Documentation. If you have a question or need help, post a question in the [*
Proposed change(s):

> Community chats allow users to communicate in various channels, each with specific topics like Packaging, Cloud, and Documentation. If you have a question or need help, post a question in the [*General*](https://chat.almalinux.org/almalinux/channels/town-square) channel or in the relevant channel for assistance.

2024-03-01 18:34 UTC, codyro commented on docs/Help-and-Support.md
> +You can receive information, announcements, news letters, and updates over email by subscribing to the [AlmaLinux Mailing Lists](http://lists.almalinux.org/).
```
[AlmaLinux Mailing Lists](http://lists.almalinux.org/).
```

to (link to `https`)

```
> [AlmaLinux Mailing Lists](https://lists.almalinux.org/).
```

2024-03-01 18:34 UTC, codyro commented on docs/Help-and-Support.md
> +AlmaLinux OS also provides forums for sharing information and assistance inside the Community. Subforum based on categories for the convenience of locating a relevant one.
> AlmaLinux OS also provides public forums for free information sharing and assistance from other AlmaLinux members. Additional Subforum categories foster conversations around a specific aspect of AlmaLinux.

2024-03-01 18:34 UTC, codyro commented on docs/Help-and-Support.md
> +Please, note, that outputs shared via [https://paste.almalinux.org/](https://paste.almalinux.org/) expire 1 hour to 1 week.
We can allow 1 day - indefinite. I just need to make sure no one has existing pastes that they need (as its stored in memory ATM). 

cc @jonathanspw

2024-03-03 01:03 UTC, codyro commented on docs/Help-and-Support.md
> +Please, note, that outputs shared via [https://paste.almalinux.org/](https://paste.almalinux.org/) expire 1 hour to 1 week.
This has been adjusted to allow longer expiry for pastes + persistence. You can safely remove this warning now.

<img width="373" alt="image" src="https://github.com/AlmaLinux/wiki/assets/196810/5a227d85-7931-42e8-b6e2-33d07370959d">

2024-03-05 15:53 UTC, sboldyreva commented
@codyro done, thank you for the review!

2024-03-05 16:43 UTC, codyro approved these changes

2024-03-25 15:22 UTC, merged