Added guide to use EC2 Instance Connect
AlmaLinux/wiki pull request #363
Opened 2024-02-29 18:03 UTC by sboldyreva

2024-02-29 18:04 UTC, sboldyreva commented
@LKHN please review

2024-03-05 11:51 UTC, LKHN requested changes

2024-03-05 12:56 UTC, sboldyreva commented on docs/cloud/EC2-instance-connect.md
> +See the [Amazon AWS page](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2-instance-connect/ssh.html) for more command line options.
@LKHN done, please check

2024-03-05 13:25 UTC, LKHN approved these changes

2024-03-05 13:26 UTC, LKHN approved these changes
LGTM. Thanks a lot!

2024-03-05 14:49 UTC, andrewlukoshko approved these changes

2024-03-05 14:49 UTC, merged