add 2024-09-04 alesco minutes
AlmaLinux/wiki pull request #486
Opened 2024-09-06 15:03 UTC by jonathanspw

2024-09-06 15:05 UTC, andrewlukoshko approved these changes

2024-09-06 15:10 UTC, Conan-Kudo requested changes

2024-09-06 15:10 UTC, Conan-Kudo commented on docs/alesco/meeting-minutes/2024-09-04.md
> +# ALESCo Meeting Minutes (2024-07-24)
Wrong date.

2024-09-06 15:33 UTC, LKHN approved these changes

2024-09-06 15:46 UTC, codyro approved these changes
Looks fine once the date is fixed.

2024-09-06 15:47 UTC, bathomas approved these changes

2024-09-06 15:47 UTC, bathomas commented on docs/alesco/meeting-minutes/2024-09-04.md
> +- Cody: Old business: tabled discussion about adding spice to EL9 from previous meeting
```suggestion
- Cody: Old business: tabled discussion about adding SPICE to EL9 from previous meeting
```

2024-09-07 01:13 UTC, Conan-Kudo approved these changes

2024-09-09 19:12 UTC, bennyvasquez approved these changes

2024-09-09 20:28 UTC, merged