Added ELevate Changelog
AlmaLinux/wiki pull request #500
Opened 2024-09-19 16:08 UTC by sboldyreva

Added a page for users to track ELevate Changes besides our blog 

Do not merge yet, awaits release date

2024-09-19 20:57 UTC, bennyvasquez commented
yesssssssssss. Thank you, @sboldyreva!

2024-09-23 18:36 UTC, bennyvasquez approved these changes
@sboldyreva once the release date has been updated, this one is ready to go!

2024-09-24 12:08 UTC, andrewlukoshko requested changes

2024-09-24 12:08 UTC, andrewlukoshko commented on docs/elevate/Changelog.md
> +* Added **Docker CE** support ffor all supported operating systems.
typo

2024-09-24 12:12 UTC, andrewlukoshko approved these changes

2024-09-24 12:12 UTC, merged