Alesco Meeting 10/02/2024 Minutes
AlmaLinux/wiki pull request #513
Opened 2024-10-17 14:31 UTC by codyro

Excuse the belated publishing.

2024-10-17 14:43 UTC, Conan-Kudo requested changes

2024-10-17 14:43 UTC, Conan-Kudo commented on docs/alesco/meeting-minutes/2024-10-02.md
> +	- Neil:	Suggested that releasing without EPEL support might hinder adoption.
`Neil` -> `Neal`

2024-10-17 14:43 UTC, Conan-Kudo commented on docs/alesco/meeting-minutes/2024-10-02.md
> +	- Neil: Warned that releasing AlmaLinux 10 without EPEL support for x86_64 v2 could impede adoption/usage
Ditto

2024-10-17 14:43 UTC, Conan-Kudo commented on docs/alesco/meeting-minutes/2024-10-02.md
> +	-	Neil: Proposed adding sections about the benefit to AlmaLinux and feedback from the community/marketing perspective
Ditto.

2024-10-17 14:43 UTC, Conan-Kudo commented on docs/alesco/meeting-minutes/2024-10-02.md
> +    - Neil: Jonathan and him can draft up the x86_64_v2 one as an example
Ditto

2024-10-17 14:51 UTC, Conan-Kudo approved these changes

2024-10-17 14:51 UTC, jonathanspw approved these changes

2024-10-18 14:59 UTC, LKHN approved these changes

2024-10-22 19:34 UTC, jonathanspw commented
poke @andrewlukoshko @bennyvasquez

2024-10-22 20:15 UTC, bennyvasquez approved these changes

2024-10-22 20:39 UTC, andrewlukoshko approved these changes

2024-10-22 20:40 UTC, merged